<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE edificio [

<!ELEMENT edificio (enderezo, dataConstrucion, material?)>

<!ELEMENT enderezo (rua, numero, poboacion, provincia, codigoPostal)>

<!ELEMENT rua (#PCDATA)>

<!ELEMENT numero (#PCDATA)>

<!ELEMENT poboacion (#PCDATA)>

<!ELEMENT provincia (#PCDATA)>

<!ELEMENT codigoPostal (#PCDATA)>

<!ELEMENT dataConstrucion EMPTY>

<!ATTLIST dataConstrucion

mes CDATA #REQUIRED

ano CDATA #REQUIRED>

<!ELEMENT material (#PCDATA)>

<!ATTLIST edificio

valor CDATA #IMPLIED

alquiler (verdadeiro|falso) #REQUIRED>

]>

<edificio valor="120" alquiler="verdadeiro"> 
<enderezo>
  <rua>Trasdeza</rua>
  <numero>48</numero>
  <poboacion>Silleda</poboacion>
  <provincia>Pontevedra</provincia>
  <codigoPostal>36540</codigoPostal>
</enderezo>
<dataConstrucion mes="Noviembre" ano="2010"/>

</edificio>