<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE famosos [

<!ELEMENT famosos (famoso*)>

<!ELEMENT famoso ((nome | apodo), profesion+, dataNacimiento?)>

<!ELEMENT nome (#PCDATA)>

<!ELEMENT apodo (#PCDATA)>

<!ELEMENT profesion (#PCDATA)>

<!ELEMENT dataNacimiento (#PCDATA)>
]>

<famosos>

<famoso>

<nome>Michael Jackson</nome>

<profesion>cantante</profesion>

</famoso>

<famoso>

<apodo>La voz</apodo>

<profesion>cantante</profesion>

<profesion>actor</profesion>
<dataNacimiento>12-dec-1915</dataNacimiento>
</famoso>

</famosos>