<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE contactos [

<!ELEMENT contactos (contacto*)>

<!ELEMENT contacto (nome, fixo?, mobil+,correo*)>

<!ELEMENT nome (#PCDATA)>

<!ELEMENT fixo (#PCDATA)>

<!ELEMENT mobil (#PCDATA)>

<!ELEMENT correo (#PCDATA)>

]>

<contactos>

<contacto>
<nome>Xoel</nome>
<mobil>98658123</mobil>
</contacto>

<contacto>
<nome>Noa</nome>
<fixo>998899889</fixo>
<mobil>644432344</mobil>
<correo>noa@omeucorreo.com</correo>
</contacto>
</contactos>